### ISSUE TITLE
Pass mouse and keyboard back to remote vnc

### ISSUE THREAD

**Issue by FreeLikeGNU** [norihiro/obs-vnc#12]
thank you for this awesome plugin!

I propose the ability to pass keyboard and mouse (or at least mouse) back to the vnc host.  

Could it work from the projection view when the pointer is over the vnc input and sends the position relative to the size of the displayed vnc input to that host? 

Use case:  I have a number of vnc hosts arranged on the projection, I'd like to navigate within any one of those hosts from the projection screen.

**Comment by norihiro** [comment]
Plugin API has an interface for keyboard and mouse.
I'm not sure the projector window can accept the interaction but it's worth to try.

**Comment by norihiro** [comment]
Unfortunately, Projector Window does not have the ability to send mouse and key event to the source.
A button is shown when selecting the source that has interact capability. Clicking the button, a dedicated window for the source will appear and the window accept mouse and key event.

Not only updating this plugin, we need to request OBS Studio to pass the mouse & key event on the Projector Window to the source.

**Comment by norihiro** [comment]
A recently released plugin [obs-source-dock](https://github.com/exeldro/obs-source-dock) can pass the mouse and keyboard input to the source. It might be useful for your case.
I'd like to note that the interaction cannot go through a scene, need to have a lot of docks displaying the vnc sources. It could cause a performance issue.

**Comment by norihiro** [comment]
The new version 0.2.3 of [Source Dock](https://obsproject.com/forum/resources/source-dock.1317/) has ability to interact with scene items. I think it would be helpful for your application.
