### ISSUE TITLE
Feature request : choose which screen to capture

### ISSUE THREAD

**Issue by jpvincent** [norihiro/obs-vnc#2]
Hi
first, thanks for this plugin !
Until now, in order to mix video on PC 1 with one of the screen of PC 2 (a Mac), I used the VNC Viewer, but it lacks the posibility of picking up only one of the 2 screens, so I had to crop it in OBS. My other option is to cast the good screen from PC2 with NDI, but it's taking a lot of CPU, defeating the purpose of my dual computer setup.

Can you provide an option in this VNC plugin for picking up of the screens ?

thanks !

**Comment by norihiro** [comment]
Unfortunately, VNC's protocol does not have a feature to send the multi-screen information. It only sends width and height of the whole desktop.
Is there any concerns or difficulties if using crop in transform?

**Comment by jpvincent** [comment]
It just that sending my whole desktop instead of one of both takes a lot of CPU on the computer.
Croping on the other end works fine, it just adds a bit more configuration for croping and rescaling.

Thanks for your answer !
