### ISSUE TITLE
VNC Source does not show up on the list of Sources/Add menu in macOS 

### ISSUE THREAD

**Issue by SamCCb** [norihiro/obs-vnc#24]
After tuning the dmg file, and copying the folder obs-vnc under OBS.app, the ops-vnc option is not implemented when I restart OBS.

**Your setup**
- Name and version of VNC server : Screen Sharing macOS 556.1
- VNC use to share a local computer screen, perfectly working
- Mac OS Big Sur 11.5. 2 and OBS 27.0.1 (Mac)
- Version of the plugin 0.4.0

**Expected behavior**
As OBS Studio for PC, when installing a Plugin is in the "tool" menu. I was expected to see obs-vnc in this menu or in the Sources like a Bowser capture by exemple.

**Actual behavior**
OBS-VNC is invisible, not showed anywhere in OBS studio.

**Additional context**

**Comment by norihiro** [comment]
>  I was expected to see obs-vnc in this menu or in the Sources like a Bowser capture by exemple.

Yes, VNC Source should be found as a source like Browser and Screen Capture sources.

Could you check log file of OBS Studio?

1. In OBS select Help > Log Files > Upload Current Log File.
2. Click Copy URL and then paste the link here.

**Comment by SamCCb** [comment]
16:04:33.153: CPU Name: Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
16:04:33.153: CPU Speed: 3500MHz
16:04:33.153: Physical Cores: 4, Logical Cores: 4
16:04:33.153: Physical Memory: 8192MB Total
16:04:33.153: OS Name: Mac OS X
16:04:33.153: OS Version: Version 11.5.2 (Build 20G95)
16:04:33.153: Kernel Version: 20.6.0
16:04:33.164: hotkeys-cocoa: Using layout 'com.apple.keylayout.French'
16:04:33.164: Current Date/Time: 2021-08-23, 16:04:33
16:04:33.164: Browser Hardware Acceleration: true
16:04:33.164: Portable mode: false
16:04:33.269: OBS 27.0.1 (mac)
16:04:33.269: ---------------------------------
16:04:33.270: ---------------------------------
16:04:33.270: audio settings reset:
16:04:33.270: 	samples per sec: 48000
16:04:33.270: 	speakers:        2
16:04:33.271: ---------------------------------
16:04:33.271: Initializing OpenGL...
16:04:33.296: Loading up OpenGL on adapter ATI Technologies Inc. AMD Radeon Pro 575 OpenGL Engine
16:04:33.296: OpenGL loaded successfully, version 4.1 ATI-4.6.20, shading language 4.10
16:04:33.398: ---------------------------------
16:04:33.398: video settings reset:
16:04:33.398: 	base resolution:   1920x1080
16:04:33.398: 	output resolution: 424x240
16:04:33.398: 	downscale filter:  Bicubic
16:04:33.398: 	fps:               60/1
16:04:33.398: 	format:            NV12
16:04:33.398: 	YUV mode:          709/Partial
16:04:33.398: NV12 texture support not available
16:04:33.398: Audio monitoring device:
16:04:33.398: 	name: Par défaut
16:04:33.398: 	id: default
16:04:33.398: ---------------------------------
16:04:33.399: Failed to load 'en-US' text for module: 'decklink-captions.so'
16:04:33.401: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
16:04:33.407: os_dlopen(libpython3.9.dylib->libpython3.9.dylib): dlopen(libpython3.9.dylib, 257): image not found
16:04:33.407: 
16:04:33.407: [Python] Could not load library: libpython3.9.dylib
16:04:33.563: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
16:04:33.563: No blackmagic support
16:04:33.565: [mac-virtualcam] version=1.3.0
16:04:33.647: obs_register_encoder: Encoder id 'com.apple.videotoolbox.videoencoder.h264.gva' already exists!  Duplicate library?
16:04:33.647: [VideoToolbox encoder]: Adding VideoToolbox H264 encoders
16:04:33.651: [obs-browser]: Version 2.14.3
16:04:33.651: [obs-browser]: CEF Version 85.0.0-HEAD.2273+g93b66a0+chromium-85.0.4183.121
16:04:33.681: VLC found, VLC video source enabled
16:04:33.681: ---------------------------------
16:04:33.681:   Loaded Modules:
16:04:33.681:     vlc-video.so
16:04:33.681:     text-freetype2.so
16:04:33.681:     rtmp-services.so
16:04:33.681:     obs-x264.so
16:04:33.681:     obs-vst.so
16:04:33.681:     obs-transitions.so
16:04:33.681:     obs-outputs.so
16:04:33.681:     obs-filters.so
16:04:33.681:     obs-ffmpeg.so
16:04:33.681:     obs-browser.so
16:04:33.681:     mac-vth264.so
16:04:33.681:     mac-virtualcam.so
16:04:33.681:     mac-syphon.so
16:04:33.681:     mac-decklink.so
16:04:33.681:     mac-capture.so
16:04:33.681:     mac-avcapture.so
16:04:33.681:     image-source.so
16:04:33.681:     frontend-tools.so
16:04:33.681:     decklink-ouput-ui.so
16:04:33.681:     decklink-captions.so
16:04:33.681:     coreaudio-encoder.so
16:04:33.681: ---------------------------------
16:04:33.681: ==== Startup complete ===============================================
16:04:33.696: All scene data cleared
16:04:33.696: ------------------------------------------------
16:04:33.743: coreaudio: device 'Built-in Microphone' initialized
16:04:33.743: [Loaded global audio device]: 'Mic/Aux'
16:04:33.750: Switched to scene 'Scene 2'
16:04:33.751: ------------------------------------------------
16:04:33.751: Loaded scenes:
16:04:33.751: - scene 'Scene 2':
16:04:33.751:     - source: 'WinPc' (window_capture)
16:04:33.751: ------------------------------------------------
16:04:33.790: adding 42 milliseconds of audio buffering, total audio buffering is now 42 milliseconds (source: Mic/Aux)
16:04:33.790:

**Comment by norihiro** [comment]
It looks the necessary plugin file `obs-vnc.so` is not loaded.

Would you ensure this file is there?
`/Library/Application Support/obs-studio/plugins/obs-vnc/bin/obs-vnc.so`

If not, I'm afraid there is no folder `/Library/Application Support/obs-studio/plugins` and failed to copy the plugin into the folder when you installed from the DMG package.
In that case, at first please create a folder `/Library/Application Support/obs-studio/plugins` and then copy `obs-vnc` into the folder `plugins` again.

I think this guide would be helpful. (This is for my other plugin but the steps should be same.)
https://github.com/norihiro/obs-color-monitor/wiki/Install-MacOS

I'm sorry for your inconvenience.

**Comment by SamCCb** [comment]
Well, thank you !
After creating folders under 'Application Support', rebooting, everything was fine. Thank you again.

**Comment by norihiro** [comment]
I’m glad to hear it works fine.
Thanks.
