### ISSUE TITLE
Dual display output

### ISSUE THREAD

**Issue by kaiwhite95** [norihiro/obs-vnc#26]
Is it possible to show the second screen from a computer running Ultra VNC in OBS Studio without having to go into VNC viewer and changing it to dual screen. Maybe an option in OBS studio somewhere to choose both screens or something

**Comment by norihiro** [comment]
The VNC protocol itself does not have the ability to select the display. From the VNC, the display looks just one large rectangle even if there are multiple displays.

I'd like to suggest using `crop` feature in the OBS Studio.
1. Select your VNC source in the `Sources` list.
2. Right click, select `Transform` and `Edit Transform` to open the dialog. Or, hit Ctrl + E.
3. Put appropriate numbers into `Crop` / `Left`, `Right`, `Top`, `Bottom`.
   ![obs-crop-source](https://user-images.githubusercontent.com/780600/158580994-ef8a46b9-82f0-43b8-b718-19b66bcafc00.png)
If you have two displays tiled left and right, and want to choose the right display, input the width of the left display into `Crop`/`Left`. If the height of the left display is taller than the right display, input the difference into `Bottom`. Leave others unchanged.

**Comment by kaiwhite95** [comment]
As default it doesn't show as one big rectangle, just screen one. To get it to show as one big rectangle I have to open UltraVNC viewer and change it to show both screens.

**Comment by norihiro** [comment]
I remember I have written about that in [README.md](https://github.com/norihiro/obs-vnc#windows).
