### ISSUE TITLE
Doesn't show up as an input or anywhere else

### ISSUE THREAD

**Issue by markcharlesobrien** [norihiro/obs-vnc#29]
Trying to get this to work. Installed as instructed, but it doesn't show up as a source, or in the Tools menu.

Here are my logs: [https://obsproject.com/logs/pzvofX0ESVWsQdI_](https://obsproject.com/logs/pzvofX0ESVWsQdI_)

**Comment by norihiro** [comment]
Thank you for creating this issue.
I remember I forgot to create this plugin for OBS 28 on ARM architecture.
It's under development at https://github.com/norihiro/obs-vnc/pull/27 but I forgot to continue working on that.

**Comment by markcharlesobrien** [comment]
Any progress on this?

**Comment by norihiro** [comment]
I have a trial build but I'm not sure if it works. You can find `artifact` at the bottom of this page. It includes a package for Apple Silicon.
https://github.com/norihiro/obs-vnc/actions/runs/3337482271

I use the same build flow for norihiro/obs-text-pthread and someone reported it does not work on Apple Silicon. I don't think above package will work.

**Comment by NorseGaud** [comment]
Hi @norihiro , I can work with you to test this. Would be happy to sponsor you for a while to in order to maintain and keep up to date plugins for the latest OBS and arm64. Ping me if you're interested.

**Comment by norihiro** [comment]
The version [0.5.0-rc3](https://github.com/norihiro/obs-vnc/releases/tag/0.5.0-rc3) should work on Apple Silicon. I will make a release 0.5.0 later in this week.
