### ISSUE TITLE
obs-studio-build.patch has conflicts unresolved and commited

### ISSUE THREAD

**Issue by NorseGaud** [norihiro/obs-vnc#30]
https://github.com/norihiro/obs-vnc/blob/main/ci/macos/obs-studio-build.patch

<img width="863" alt="Screen Shot 2023-05-20 at 8 25 50 PM" src="https://github.com/norihiro/obs-vnc/assets/5896030/211dbeb5-014e-45a9-a794-112145f20049">

**Comment by norihiro** [comment]
I know it's outdated and a PR #27 points to some the activity to resolve it.
